name: english_words
description: Utilities for working with English words.
version: 3.0.1
author: Filip Hracek <filip.hracek@gmail.com>
homepage: https://github.com/filiph/english_words

environment:
  sdk: '>=1.22.0 <2.0.0'

dependencies:
  string_scanner: ^1.0.1

dev_dependencies:
  benchmark_harness: ^1.0.4
  test: '>=0.12.20 <0.13.0'
